#!/usr/bin/env python3
"""Generates C# stubs replacing the WinUI XAML compiler's pass-1 output (x:Name fields,
InitializeComponent, Bindings) so that the app's C# code can be compiled on Linux, where the
real XAML compiler can't run. Only used for the local "linux-check" build; real builds use the
XAML compiler on Windows.

Usage: xaml-stubgen.py <project-dir> <out-dir>
"""
import os
import sys
import xml.etree.ElementTree as ET

XAML_NS = "http://schemas.microsoft.com/winfx/2006/xaml"
PRESENTATION_NS = "http://schemas.microsoft.com/winfx/2006/xaml/presentation"
TEMPLATE_TAGS = {"DataTemplate", "ControlTemplate", "ItemsPanelTemplate"}

# Preferred namespaces for the default XAML namespace (WinUI)
NS_PRIORITY = [
    "Microsoft.UI.Xaml.Controls",
    "Microsoft.UI.Xaml.Controls.Primitives",
    "Microsoft.UI.Xaml",
    "Microsoft.UI.Xaml.Shapes",
    "Microsoft.UI.Xaml.Media",
    "Microsoft.UI.Xaml.Media.Animation",
    "Microsoft.UI.Xaml.Media.Imaging",
    "Microsoft.UI.Xaml.Documents",
    "Microsoft.UI.Xaml.Input",
    "Microsoft.UI.Xaml.Data",
]


def load_types():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "winui-types.txt")
    by_name = {}
    with open(path) as f:
        for line in f:
            full = line.strip()
            if not full:
                continue
            ns, _, name = full.rpartition(".")
            by_name.setdefault(name, []).append(ns)
    return by_name


TYPES = load_types()


UNKNOWN = []


def resolve_default(name):
    candidates = TYPES.get(name, [])
    if not candidates and name not in ("Page", "UserControl", "Window", "Application"):
        UNKNOWN.append(name)
    for ns in NS_PRIORITY:
        if ns in candidates:
            return f"global::{ns}.{name}"
    if candidates:
        return f"global::{candidates[0]}.{name}"
    return f"global::Microsoft.UI.Xaml.Controls.{name}"


def split_tag(tag):
    if tag.startswith("{"):
        ns, _, local = tag[1:].partition("}")
        return ns, local
    return "", tag


def resolve_type(ns_uri, local):
    local = local.split(".")[0]  # property elements are filtered earlier
    if ns_uri in (PRESENTATION_NS, ""):
        return resolve_default(local)
    if ns_uri.startswith("using:"):
        return f"global::{ns_uri[len('using:'):]}.{local}"
    if ns_uri.startswith("clr-namespace:"):
        clr = ns_uri[len("clr-namespace:"):].split(";")[0]
        return f"global::{clr}.{local}"
    return resolve_default(local)


def collect_names(elem, fields, in_template=False):
    ns_uri, local = split_tag(elem.tag)
    if "." in local:  # property element (e.g. Grid.RowDefinitions)
        for child in elem:
            collect_names(child, fields, in_template)
        return
    if ns_uri in (PRESENTATION_NS, ""):
        resolve_default(local)  # records unknown element types
    if local in TEMPLATE_TAGS:
        in_template = True
    name = elem.attrib.get(f"{{{XAML_NS}}}Name") or elem.attrib.get("Name")
    if name and not in_template:
        fields.append((resolve_type(ns_uri, local), name))
    for child in elem:
        collect_names(child, fields, in_template)


def generate(xaml_path, out_dir, project_dir):
    try:
        tree = ET.parse(xaml_path)
    except ET.ParseError as e:
        print(f"XAML parse error in {xaml_path}: {e}", file=sys.stderr)
        sys.exit(1)
    root = tree.getroot()
    cls = root.attrib.get(f"{{{XAML_NS}}}Class")
    if not cls:
        return None
    ns_uri, local = split_tag(root.tag)
    base = resolve_type(ns_uri, local)
    namespace, _, class_name = cls.rpartition(".")
    fields = []
    for child in root:
        collect_names(child, fields)
    modifier = root.attrib.get(f"{{{XAML_NS}}}ClassModifier", "public")
    field_modifier = root.attrib.get(f"{{{XAML_NS}}}FieldModifier", "internal")
    lines = [
        "// <auto-generated> xaml-stubgen (linux check only) </auto-generated>",
        "#nullable disable",
        "#pragma warning disable",
        f"namespace {namespace}",
        "{",
        f"    {modifier} partial class {class_name} : {base}",
        "    {",
    ]
    for type_name, name in fields:
        lines.append(f"        {field_modifier} {type_name} {name};")
    is_app = local == "Application"
    lines.append("        public void InitializeComponent() { }")
    if not is_app:
        lines.append("        private __StubBindings Bindings = new __StubBindings();")
        lines.append("        private sealed class __StubBindings { public void Update() { } public void Initialize() { } public void StopTracking() { } }")
    lines.append("    }")
    if is_app:
        lines.append("    public static class __StubProgram { public static void Main(string[] args) { } }")
    lines.append("}")
    rel = os.path.relpath(xaml_path, project_dir)
    out_path = os.path.join(out_dir, rel + ".stub.cs")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return out_path


def main():
    project_dir = os.path.abspath(sys.argv[1])
    out_dir = os.path.abspath(sys.argv[2])
    if os.path.isdir(out_dir):
        for dirpath, _, files in os.walk(out_dir):
            for f in files:
                if f.endswith(".stub.cs"):
                    os.remove(os.path.join(dirpath, f))
    count = 0
    for dirpath, dirnames, files in os.walk(project_dir):
        dirnames[:] = [d for d in dirnames if d not in ("bin", "obj")]
        for f in files:
            if f.endswith(".xaml"):
                if generate(os.path.join(dirpath, f), out_dir, project_dir):
                    count += 1
    print(f"Generated {count} XAML stubs in {out_dir}")
    if UNKNOWN:
        print("error XAML: unknown element types (typo?): " + ", ".join(sorted(set(UNKNOWN))))
        sys.exit(1)


if __name__ == "__main__":
    main()
